services:
  - type: web
    name: coding-interview-platform
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "https://vncode.onrender.com"
      - key: REDIS_URL
        value: "rediss://default:AawoAAIncDJhZjhmYWFiMzI2YTY0M2JlOTBjMzFiNGE2NzA2MzlmYnAyNDQwNzI@concrete-opossum-44072.upstash.io:6379"
