services:
  - type: web
    name: coding-interview-platform
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "https://vncode.onrender.com"
      - key: REDIS_URL
        sync: false
